### ISSUE TITLE
Consider plurals to be "uncommon"

### ISSUE THREAD

**Issue by mgiuca** [jakearchibald/wordle-analyzer#12]
As far as I can tell, Wordle has never had a plural word. It still accepts plurals, and it could have one in the future (not cheating by looking at the word list), but I think it's reasonable to deprioritize plurals when ordering guesses.

(If you don't have a good way to determine what word is plural, an OK heuristic would just be words that are another word with an S on the end.)

**Comment by jakearchibald** [comment]
Ohh that's a good idea!

**Comment by Cirzen** [comment]
More than that, there are no 3rd person versions of 4 letter verbs with an -s ending (e.g. "emits") either. In fact, I've just done a scan, the only words ending with s in the "possible answers" list are:
abyss, amass, amiss, basis, bless, bliss, bonus, brass, chaos, chess, class, crass, cress, cross, dress, dross, ethos, fetus, ficus, floss, focus, glass, gloss, grass, gross, guess, humus, locus, lupus, minus, mucus, press, rebus, torus, truss, virus
And that was from the pre-NYT amendments, so "fetus" isn't in there any more either.

**Comment by jakearchibald** [comment]
I finally did this, in 4ac193a5b45d73a54eba138ab550f7a3b6f05e41 and edc718c55b40a946559aaff81631b3667c9f9473

**Comment by mgiuca** [comment]
That's great but... wow did this change the start word from LARES to SOARE? End of an era!

**Comment by jakearchibald** [comment]
I know right! It was marginal between those two words, so it was enough to change it
