### ISSUE TITLE
Store guesses in history state

### ISSUE THREAD

**Issue by jakearchibald** [jakearchibald/wordle-analyzer#5]
Going back to the first page should restore the guesses, even if there's a page load.

**Comment by paoloricciuti** [comment]
I was thinking of contributing to this project with a "Save first N words" in the homepage do that if someone (like me) often uses the same first word (or even the first two) every day could avoid to retype them every day.

If you are ok I might take care of this too.

**Comment by jakearchibald** [comment]
Fixed in 1510dade55f598f3b480836d0ac2f504f4aebf29

**Comment by jakearchibald** [comment]
@paoloricciuti turned out I'd already done this but forgot to close it!

As for the other idea, it sounds good, although the tricky part is the UX. What were you thinking? Maybe it could be a little 🔒 icon next to each guess meaning "remember this for next time"?

**Comment by paoloricciuti** [comment]
I was thinking of a small input type number under the guesses inlined with the sentence.

`Remember the first <input type=number /> guesses`
